// Builds the GitHub Pages landing page from README.md.
//
// The README is the single source of truth (its API section is regenerated by
// `npm run docgen`), so this script just renders it to a styled, standalone
// index.html under ./site — no content is duplicated. Run `npm run docs:site`.

import { readFileSync, writeFileSync, mkdirSync, readFileSync as read } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(read(resolve(root, 'package.json'), 'utf8'));
const outDir = resolve(root, 'site');

function decodeEntities(s) {
  return s
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

// GitHub's heading-slug algorithm, so the README's docgen index anchors
// (e.g. #getvolume-) resolve on the generated page too. Order matters: trim,
// then strip punctuation, then whitespace -> hyphen with no final trim or
// collapse — that's what keeps the trailing dash and double dashes GitHub
// itself emits.
function githubSlug(text) {
  return decodeEntities(text)
    .replace(/<[^>]+>/g, '')
    .trim()
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s/g, '-');
}

function stripTags(html) {
  return html.replace(/<[^>]+>/g, '');
}

let markdown = readFileSync(resolve(root, 'README.md'), 'utf8');

// The docgen wrapper comments are noise on a rendered page.
markdown = markdown
  .replace(/<docgen-index>|<\/docgen-index>|<docgen-api>|<\/docgen-api>/g, '')
  .replace(/<!--Update the source file JSDoc[^>]*-->/g, '');

marked.setOptions({ gfm: true, breaks: false });

let bodyHtml = marked.parse(markdown);

// Give every heading a GitHub-compatible id so in-page anchors work, and
// collect h2/h3 to build a sidebar table of contents.
const toc = [];
bodyHtml = bodyHtml.replace(/<h([1-6])>([\s\S]*?)<\/h\1>/g, (_m, level, inner) => {
  const id = githubSlug(stripTags(inner));
  const depth = Number(level);
  if (depth === 2 || depth === 3) toc.push({ depth, id, text: stripTags(inner) });
  return `<h${level} id="${id}"><a class="anchor" href="#${id}" aria-label="Link to this section">#</a>${inner}</h${level}>`;
});

const tocHtml = toc
  .map((t) => `<a class="toc-link toc-h${t.depth}" href="#${t.id}">${t.text}</a>`)
  .join('\n');

const repoUrl = (pkg.repository?.url || '')
  .replace(/^git\+/, '')
  .replace(/\.git$/, '');
const npmUrl = `https://www.npmjs.com/package/${pkg.name}`;
const year = new Date().getFullYear();

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${pkg.name} — ${pkg.description ?? ''}</title>
<meta name="description" content="${(pkg.description ?? '').replace(/"/g, '&quot;')}" />
<meta property="og:title" content="${pkg.name}" />
<meta property="og:description" content="${(pkg.description ?? '').replace(/"/g, '&quot;')}" />
<meta property="og:type" content="website" />
<link rel="preconnect" href="https://cdnjs.cloudflare.com" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css" media="(prefers-color-scheme: light)" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" media="(prefers-color-scheme: dark)" />
<style>
:root {
  --bg: #ffffff;
  --bg-soft: #f5f5f7;
  --surface: #ffffff;
  --border: #e3e3e8;
  --text: #1d1d1f;
  --text-soft: #56565b;
  --accent: #0a84ff;
  --accent-soft: rgba(10, 132, 255, 0.12);
  --code-bg: #f6f7f9;
  --shadow: 0 1px 3px rgba(0, 0, 0, 0.06), 0 8px 30px rgba(0, 0, 0, 0.05);
  color-scheme: light dark;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0b0b0f;
    --bg-soft: #141419;
    --surface: #16161c;
    --border: #2a2a33;
    --text: #f2f2f7;
    --text-soft: #a0a0aa;
    --accent: #409cff;
    --accent-soft: rgba(64, 156, 255, 0.16);
    --code-bg: #1a1a22;
    --shadow: 0 1px 3px rgba(0, 0, 0, 0.4), 0 8px 30px rgba(0, 0, 0, 0.35);
  }
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; scroll-padding-top: 84px; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 16px/1.65 -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

/* Top bar */
header.topbar {
  position: sticky; top: 0; z-index: 50;
  display: flex; align-items: center; gap: 14px;
  padding: 12px 22px;
  background: color-mix(in srgb, var(--bg) 82%, transparent);
  backdrop-filter: saturate(180%) blur(18px);
  -webkit-backdrop-filter: saturate(180%) blur(18px);
  border-bottom: 1px solid var(--border);
}
.topbar .logo { font-size: 20px; }
.topbar .name { font-weight: 650; letter-spacing: -0.01em; }
.topbar .spacer { flex: 1; }
.topbar .links { display: flex; gap: 8px; }
.topbar .links a {
  font-size: 13.5px; font-weight: 550; color: var(--text-soft);
  padding: 6px 12px; border-radius: 999px; border: 1px solid var(--border);
}
.topbar .links a:hover { color: var(--text); border-color: var(--accent); text-decoration: none; }

/* Hero */
.hero {
  padding: 68px 22px 52px;
  text-align: center;
  background: radial-gradient(1200px 400px at 50% -80px, var(--accent-soft), transparent 70%);
  border-bottom: 1px solid var(--border);
}
.hero .badge {
  display: inline-block; font-size: 12.5px; font-weight: 600; letter-spacing: 0.02em;
  color: var(--accent); background: var(--accent-soft);
  padding: 5px 12px; border-radius: 999px; margin-bottom: 20px;
}
.hero h1 {
  margin: 0 0 14px; font-size: clamp(32px, 6vw, 52px); line-height: 1.05;
  letter-spacing: -0.03em; font-weight: 750;
}
.hero p { max-width: 640px; margin: 0 auto; font-size: 18px; color: var(--text-soft); }
.hero .cta { margin-top: 30px; display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }
.hero .cta a {
  font-weight: 600; font-size: 15px; padding: 12px 22px; border-radius: 12px;
}
.hero .cta .primary { background: var(--accent); color: #fff; box-shadow: var(--shadow); }
.hero .cta .primary:hover { text-decoration: none; filter: brightness(1.05); }
.hero .cta .ghost { border: 1px solid var(--border); color: var(--text); }
.hero .cta .ghost:hover { text-decoration: none; border-color: var(--accent); }

/* Layout */
.layout { display: grid; grid-template-columns: 250px minmax(0, 1fr); max-width: 1180px; margin: 0 auto; gap: 40px; padding: 40px 22px 80px; }
nav.toc { position: sticky; top: 84px; align-self: start; max-height: calc(100vh - 100px); overflow: auto; font-size: 14px; }
nav.toc .toc-link { display: block; padding: 4px 0 4px 12px; color: var(--text-soft); border-left: 2px solid var(--border); }
nav.toc .toc-link:hover { color: var(--text); text-decoration: none; }
nav.toc .toc-h3 { padding-left: 26px; font-size: 13px; }
nav.toc .toc-link.active { color: var(--accent); border-left-color: var(--accent); font-weight: 600; }

/* Content */
article { min-width: 0; }
article h1 { display: none; } /* README title duplicates the hero */
article h2 { margin: 52px 0 18px; font-size: 27px; letter-spacing: -0.02em; padding-bottom: 8px; border-bottom: 1px solid var(--border); }
article h3 { margin: 34px 0 12px; font-size: 20px; letter-spacing: -0.01em; }
article h4 { margin: 26px 0 10px; font-size: 16.5px; }
article p, article li { color: var(--text); }
article .anchor { color: var(--text-soft); opacity: 0; margin-left: -18px; padding-right: 6px; font-weight: 400; }
article h2:hover .anchor, article h3:hover .anchor, article h4:hover .anchor { opacity: 0.6; }
article .anchor:hover { opacity: 1; text-decoration: none; }

article img { max-width: 100%; }
article code {
  font: 13.5px/1.5 ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
  background: var(--code-bg); padding: 0.15em 0.4em; border-radius: 6px;
}
article pre {
  background: var(--code-bg); border: 1px solid var(--border); border-radius: 12px;
  padding: 16px 18px; overflow-x: auto; box-shadow: var(--shadow);
}
article pre code { background: none; padding: 0; font-size: 13.5px; }

.table-wrap { overflow-x: auto; margin: 16px 0; border: 1px solid var(--border); border-radius: 12px; }
article table { border-collapse: collapse; width: 100%; font-size: 14px; }
article th, article td { text-align: left; padding: 10px 14px; border-bottom: 1px solid var(--border); vertical-align: top; }
article th { background: var(--bg-soft); font-weight: 600; }
article tr:last-child td { border-bottom: none; }
article td code, article th code { white-space: nowrap; }

article hr { border: none; border-top: 1px solid var(--border); margin: 32px 0; }
article blockquote { margin: 16px 0; padding: 8px 16px; border-left: 3px solid var(--accent); background: var(--accent-soft); border-radius: 0 8px 8px 0; }

footer { border-top: 1px solid var(--border); padding: 30px 22px; text-align: center; color: var(--text-soft); font-size: 13.5px; }

@media (max-width: 860px) {
  .layout { grid-template-columns: 1fr; }
  nav.toc { display: none; }
}
</style>
</head>
<body>
<header class="topbar">
  <span class="logo">🔊</span>
  <span class="name">${pkg.name}</span>
  <span class="spacer"></span>
  <span class="links">
    <a href="#install">Install</a>
    <a href="#api">API</a>
    <a href="${npmUrl}" rel="noopener">npm</a>
    <a href="${repoUrl}" rel="noopener">GitHub</a>
  </span>
</header>

<section class="hero">
  <span class="badge">iOS · MPVolumeView · Capacitor ${pkg.peerDependencies?.['@capacitor/core'] ?? ''}</span>
  <h1>Native system volume<br />for Capacitor</h1>
  <p>${pkg.description ?? ''}</p>
  <div class="cta">
    <a class="primary" href="#install">Get started</a>
    <a class="ghost" href="${repoUrl}" rel="noopener">View on GitHub</a>
  </div>
</section>

<div class="layout">
  <nav class="toc" aria-label="Table of contents">
${tocHtml}
  </nav>
  <article>
${bodyHtml}
  </article>
</div>

<footer>
  <p>${pkg.name} v${pkg.version} · MIT License · Built from README.md · © ${year} ${pkg.author?.name ?? ''}</p>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/typescript.min.js"></script>
<script>
  document.querySelectorAll('pre code').forEach((el) => { try { hljs.highlightElement(el); } catch (e) {} });
  // Wrap tables so wide docgen tables scroll instead of blowing out the layout.
  document.querySelectorAll('article table').forEach((t) => {
    if (t.parentElement.classList.contains('table-wrap')) return;
    const w = document.createElement('div'); w.className = 'table-wrap';
    t.replaceWith(w); w.appendChild(t);
  });
  // Highlight the current section in the sidebar as you scroll.
  const links = [...document.querySelectorAll('nav.toc .toc-link')];
  const byId = new Map(links.map((l) => [l.getAttribute('href').slice(1), l]));
  const spy = new IntersectionObserver((entries) => {
    entries.forEach((e) => {
      if (!e.isIntersecting) return;
      links.forEach((l) => l.classList.remove('active'));
      byId.get(e.target.id)?.classList.add('active');
    });
  }, { rootMargin: '-80px 0px -70% 0px' });
  document.querySelectorAll('article h2[id], article h3[id]').forEach((h) => spy.observe(h));
</script>
</body>
</html>
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'index.html'), html);
// .nojekyll keeps GitHub Pages from running Jekyll over the output.
writeFileSync(resolve(outDir, '.nojekyll'), '');
console.log(`Wrote ${resolve(outDir, 'index.html')}`);
